<?php
/********************************************************************************
 *                                Warning@
 * 	------------------------------------------------------------------------
 * 						    DO NOT EDIT THIS FILE
 *	------------------------------------------------------------------------
 * 
 *  					   Copyright (C) Andrija Mićić
 * 					   	   https://www.studiobeograd.com
 *
 ********************************************************************************/

$theme_includes = apply_filters( 'andrija_micic_includes',
	array(	 'theme-functions.php',
			'recipe-module.php',
			'custom-functions.php',
			));
			
foreach ( $theme_includes as $include ) { locate_template( $include, true ); }

/**********************************************************************************************************
 * 
 *     Do not edit this file.
 *     To add custom PHP functions to the theme, 
 *     create a child theme (https://www.studiobeograd.com/docs/child-theme) and add it to the child theme functions.php file.
 *
 *
***********************************************************************************************************/